from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
import os
from datetime import datetime

class ReportService:
    def generate_verification_report(self, record, output_path: str):
        doc = SimpleDocTemplate(output_path, pagesize=A4)
        styles = getSampleStyleSheet()
        story = []

        # Custom Styles
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor("#0056b3"),
            alignment=1, # Center
            spaceAfter=20
        )
        
        # Header
        story.append(Paragraph("CertiGuard AI - Verification Report", title_style))
        story.append(Paragraph(f"Reference ID: {record.verification_id}", styles['Normal']))
        story.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        story.append(Spacer(1, 24))

        # Result Summary
        status_color = colors.green if record.status == "Genuine" else colors.orange if record.status == "Suspicious" else colors.red
        story.append(Paragraph(f"VERIFICATION STATUS: <b>{record.status.upper()}</b>", 
                               ParagraphStyle('Status', parent=styles['Normal'], fontSize=16, textColor=status_color)))
        story.append(Paragraph(f"Risk Factor: {record.risk_score:.1f}%", styles['Normal']))
        story.append(Spacer(1, 16))

        # Extracted Data Table
        data = [
            ["Field", "Extracted Value"],
            ["Candidate Name", record.extracted_data.get("candidate_name") or "N/A"],
            ["Issuer/Institution", record.extracted_data.get("issuer_name") or "N/A"],
            ["Certificate ID", record.extracted_data.get("certificate_id") or "N/A"],
            ["Issue Date", record.extracted_data.get("issue_date") or "N/A"],
        ]
        
        t = Table(data, colWidths=[150, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0056b3")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('PADDING', (0, 0), (-1, -1), 12),
        ]))
        story.append(t)
        story.append(Spacer(1, 24))

        # Observations / Reasons
        if record.reasons:
            story.append(Paragraph("System Observations:", styles['Heading3']))
            for reason in record.reasons:
                story.append(Paragraph(f"• {reason}", styles['Normal']))
            story.append(Spacer(1, 24))

        # Final Footer
        story.append(Spacer(1, 50))
        story.append(Paragraph("This report was generated by CertiGuard AI forensic engine.", styles['Normal']))
        story.append(Paragraph("Certified Verification Authority", styles['Italic']))

        doc.build(story)
        return output_path

report_service = ReportService()
